name: app_analysis
version: 1.0.0
homepage: https://github.com/marchdev-tk/app_analysis
repository: https://github.com/marchdev-tk/app_analysis
issue_tracker: https://github.com/marchdev-tk/app_analysis/issues
description: app_analysis description

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # core
  cross_platform: ^3.0.1

  # analysis
  battery_info: ^1.1.1
  cpu_reader: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
