name: app_analysis
version: 0.2.5
homepage: https://github.com/marchdev-tk/app_analysis
repository: https://github.com/marchdev-tk/app_analysis
issue_tracker: https://github.com/marchdev-tk/app_analysis/issues
description: Package that provides an ability to track device stats, including CPU/RAM/Battery/Traffic.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # core
  flinq: ^2.0.2
  cross_platform: ^3.0.1
  path_provider: ^2.1.5
  http_parser: ^4.0.2

  # analysis
  battery_plus: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
