name: app_analysis
version: 0.1.0
homepage: https://github.com/marchdev-tk/app_analysis
repository: https://github.com/marchdev-tk/app_analysis
issue_tracker: https://github.com/marchdev-tk/app_analysis/issues
description: app_analysis description

environment:
  sdk: '>=2.18.6'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  # core
  flinq: ^2.0.2
  cross_platform: ^3.0.1

  # analysis
  battery_info: ^1.1.1
  cpu_reader: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
